// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXRQCha0ndvGAOeKDv6ZqQ8Tn2IiW-ADE',
    appId: '1:650119060455:web:8fa443e46c92b2197a7b42',
    messagingSenderId: '650119060455',
    projectId: 'onenote-app',
    authDomain: 'onenote-app.firebaseapp.com',
    storageBucket: 'onenote-app.appspot.com',
    measurementId: 'G-5JMP89SQPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi7T_0ZNGjyDKESORn-_Mg4iXuLG_Z4VA',
    appId: '1:650119060455:android:cdf57242df1ea20b7a7b42',
    messagingSenderId: '650119060455',
    projectId: 'onenote-app',
    storageBucket: 'onenote-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_EyCnMEUupYrFY3gl7NXpRT16D8aOlWc',
    appId: '1:650119060455:ios:76c9020098253bd47a7b42',
    messagingSenderId: '650119060455',
    projectId: 'onenote-app',
    storageBucket: 'onenote-app.appspot.com',
    iosBundleId: 'com.example.flutterOnenote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_EyCnMEUupYrFY3gl7NXpRT16D8aOlWc',
    appId: '1:650119060455:ios:76c9020098253bd47a7b42',
    messagingSenderId: '650119060455',
    projectId: 'onenote-app',
    storageBucket: 'onenote-app.appspot.com',
    iosBundleId: 'com.example.flutterOnenote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXRQCha0ndvGAOeKDv6ZqQ8Tn2IiW-ADE',
    appId: '1:650119060455:web:f30ee6efe8130ec57a7b42',
    messagingSenderId: '650119060455',
    projectId: 'onenote-app',
    authDomain: 'onenote-app.firebaseapp.com',
    storageBucket: 'onenote-app.appspot.com',
    measurementId: 'G-PFQEQQCCL3',
  );

}